@startuml ComponentDiagram

database Firebase {
    [Authentication]
    [Database]
    [Database] --> [UserData]
    [Database] --> [PublicCatAdoptionInformation]
    [Database] ..> [Authentication]
}

package FelineAdoptionAgencyApp {
    node VisualAppFunctionality {
    }
    node DataProviderFunctionality {
       AuthenticateUser ..> [Authentication]
       [Authentication] ..> LocalUserCopy
       LocalUserCopy ..> UserDataRequest
       RequestPublicCatData ..> Database
       UserDataRequest ..> Database
    }
    package DataService {
        
    }
}

VisualAppFunctionality --> DataService
DataService --> DataProviderFunctionality
DataProviderFunctionality --> DataService
DataService --> VisualAppFunctionality

@enduml