@startuml ComponentDiagram

database Firebase {
    [FirebaseAuthentication]
    [Firestore]
    [Firestore] --> [users]
    [Firestore] --> [cats]
    [Firestore] --> [adoptionProcesses]
    [Firestore] --> [feedback]
    [Firestore] --> [FirebaseAuthentication]
}

package FelineAdoptionAgencyApp {
       [FirebaseAuthentication] ..> User
       User ..> Firestore
       User --> MakeAdoptionRequest
       User --> Feedback
       User --> CancelAdoptionRequest
       CancelAdoptionRequest ..> Firestore
       Feedback ..> Firestore
       MakeAdoptionRequest ..> Firestore
       Cat ..> Firestore
}

@enduml